export { audit } from "./audit.js";
export { flaggedEntries } from "./audit.js";
export type { AuditOptions, RuleOverride, AuditResult, Issue, Entry } from "./audit.js";
export { formatViolations, reportText, AUDIT_FORMATS } from "./format.js";
export type { AuditFormat, ByElement, ByViolation, FlatIssue, SerializedIssue } from "./format.js";
export { DEFAULT_SEVERITY } from "./rules/index.js";
export type { Rule, Finding, RuleId, SequenceEntry, Severity } from "./rules/index.js";
export { composedDescendants } from "./dom/composed-tree.js";
export { isRuleIgnored } from "./dom/ignore.js";
export { selectorFor } from "./dom/selector.js";
export { isInteractive } from "./dom/semantics.js";
export { floatingAncestor, isScreenReaderOnly } from "./dom/visibility.js";
